export default {
  heroHeading: 'Create Stunning Logos with AI',
  heroSubheading: 'Let AI Design Your Perfect Logos for Businesses, Apps and Websites',
  heroDesc: 'Transform your brand with unique, custom logos generated by AI. No design skills required, just enter your brand name, and our AI does the rest. Start creating today!',
  logoTitle: 'Logo Title',
  logoDescription: 'Add Your Business, App or Website name for a Custom Logo.',
  logoDescTitle: 'Bring Your Logo Vision to Life',
  logoDescDesc: 'Share your ideas, themes, or inspirations to help create a logo that truly reflects your brand.',
  logoColorPaletteTitle: 'Select Your Color Palette',
  logoColorPaletteDesc: 'Choose the colors that best represent your brand personality and leave a memorable impact.',
  logoDesignTitle: "Pick Your Logo Style",
  logoDesignDesc: "Choose the logo design that most effectively reflects your brand's unique identity.",
  LogoIdeaTitle: "Share a Design Idea",
  LogoIdeaDesc: "Pick a style that best suits your vision, or skip to get a random suggestion.",

};
