export default {
    heroHeading: 'Create Stunning Logos with AI',
    heroSubheading: 'Let AI Design Your Perfect Logos for Businesses, Apps and Websites',
    heroDesc: 'Transform your brand with unique, custom logos generated by AI. No design skills required, just enter your brand name, and our AI does the rest. Start creating today!',
  };
  